spring:
  profiles:
    active: local # basic setting

server:
  port: 8080

mybatis:
  type-aliases-package: com.sample
  mapper-locations: classpath:/mapper/**/*Mapper.xml

---
# local(127.0.0.1)

spring:
  datasource:
    url: jdbc:mysql://10.101.97.88:13306/zz_test?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: nsm!@#123
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1
  config:
    activate:
      on-profile: local